openai:
  generate_model: gpt-4o-mini
  eval_model: gpt-4o

raw_transcripts_gen:
  minority_criteria: [formality, persuasiveness, filler words, transition logic]
  num_samples: 50
  output_file: data/raw/generated_transcripts.jsonl
  temperature: 1
  max_tokens: 1000

webtext_load:
  num_samples: 1000
  raw_output_file: data/raw/openwebtext_sample.jsonl

gpt_data_label:
  max_eval_tokens: 500
  webtext_label_output_file: data/labeled/label_openwebtext_sample.jsonl
  generated_label_output_file: data/labeled/label_generated_sample.jsonl

data_process:
  criteria: [formality, persuasiveness, enthusiasm, empathy, filler words, transition logic]

data_split:
  input: data/labeled/clean_label_openwebtext_sample.jsonl
  output_dir: data
  stratified_criteria: [formality, persuasiveness, transition logic]
  threshold: 6
  train_ratio: 0.8
  val_ratio: 0.1

evaluation:
  jsonl_format_in: [data/labeled/label_openwebtext_sample.jsonl]
  jsonl_generated_data_in: [data/labeled/label_generated_sample.jsonl]
  jsonl_format_out: eval/json_evaluation_metrics.txt
  jsonl_generated_data_out: eval/json_generated_evaluation_metrics.txt
  clean_webtext_data_out: data/labeled/clean_label_openwebtext_sample.jsonl
  clean_generated_data_out: data/labeled/clean_label_generated_sample.jsonl
  score_threshold: [5, 6]